### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by jodzeee** [robincornett/display-featured-image-genesis#3]
I just tried out the latest version because I want the title above the featured image. I'm getting the following error on my local dev server:

Fatal error: Cannot redeclare class Display_Featured_Image_Genesis in F:\_websites\www.client-whs-140119.dev\wp-content\plugins\display-featured-image-genesis-develop\includes\class-displayfeaturedimagegenesis.php on line 17

**Comment by robincornett** [comment]
Do you maybe also have the master (or wp.org) version activated on your site? Your error has the plugin in a `display-featured-image-genesis-develop` folder, which would correspond to the development branch, but if you were already using the plugin on the site, it would be in a directory called `display-featured-image-genesis`. If both are activated that would result in the class being declared twice.

If this is the case, can you rename, or simply delete, one of the folders? That would deactivate the second instance of the plugin automatically.

If this is not the case, I would try deleting the plugin folder completely, and adding it to your site again. Please let me know how it goes--good luck!

**Comment by jodzeee** [comment]
Oh, sorry ... I didn't look closely enough, I thought the new one was overwriting the old one. I even tried removing and reinstalling and didn't notice they were named differently. I should have been doing this while I was more awake! It works fine now. Thank you!

**Comment by robincornett** [comment]
No worries! That is one potential issue of working with multiple branches on Github--downloading the zip will append the name of the branch to the folder. I am still kicking tires on this release (it's a big one!) but hope to have it on wp.org soon. If you encounter any issues, please let me know. Thanks!
