### ISSUE TITLE
Leaves a blank Entry-header

### ISSUE THREAD

**Issue by NormanHoehne** [robincornett/display-featured-image-genesis#6]
If the option "Move Excerpts/Archive Descriptions" is active and in the entry-header only is the heading, the plugin leaves the empty entry-header in the article section. If the theme has an margin applied on the entry-header, the space between featured image and the content is going to be too big:

![image](https://cloud.githubusercontent.com/assets/10476937/20650803/97a26e42-b4d7-11e6-98a1-5b7b95973c10.png)

**Comment by robincornett** [comment]
Good catch! I think the best (maybe only reliable) way for me to tackle that is to check if the current post type supports the before entry meta--if not, I can remove the entry header open/close. I'm wondering how many users tuck other content into the entry header, without touching entry meta....if they've just removed the entry meta/post info with a `remove_action`, I don't think that I can do anything about that.

Let me push an update and maybe you can see what you think? I've tested and it does work as expected for pages.

**Comment by NormanHoehne** [comment]
Works like a charm for me! Perfect @robincornett. I'm glad my thoughts could make it into the new 2.6.2 version. :)
